name: Basic validation

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-20.04
    name: Java 11 compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          architecture: x64
          java-version: 11
      - name: Run the Maven verify phase
        run: mvn verify -pl zjazd-3